<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class MatchScoreRecordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('match_score_records')->insert([
            ['starcraft_id' => 1],
            ['starcraft_id' => 2],
            ['starcraft_id' => 3],
            ['starcraft_id' => 4],
            ['starcraft_id' => 5],
            ['starcraft_id' => 6],
            ['starcraft_id' => 7],
            ['starcraft_id' => 8],
            ['starcraft_id' => 9],
            ['starcraft_id' => 10],
            ['starcraft_id' => 11],
            ['starcraft_id' => 12],
            ['starcraft_id' => 13],
            ['starcraft_id' => 14],
            ['starcraft_id' => 15],
            ['starcraft_id' => 16],
            ['starcraft_id' => 17],
            ['starcraft_id' => 18],
            ['starcraft_id' => 19],
            ['starcraft_id' => 20],
            ['starcraft_id' => 21],
            ['starcraft_id' => 22],
            ['starcraft_id' => 23],
            ['starcraft_id' => 24],
            ['starcraft_id' => 25],
            ['starcraft_id' => 26],
            ['starcraft_id' => 27],
            ['starcraft_id' => 28],
            ['starcraft_id' => 29],
            ['starcraft_id' => 30],
            ['starcraft_id' => 31],
            ['starcraft_id' => 32],
            ['starcraft_id' => 33],
            ['starcraft_id' => 34],
            ['starcraft_id' => 35],
            ['starcraft_id' => 36],
            ['starcraft_id' => 37],
            ['starcraft_id' => 38],
            ['starcraft_id' => 39],
            ['starcraft_id' => 40],
            ['starcraft_id' => 41],
            ['starcraft_id' => 42],
            ['starcraft_id' => 43],
            ['starcraft_id' => 44],
            ['starcraft_id' => 45],
            ['starcraft_id' => 46],
            ['starcraft_id' => 47],
            ['starcraft_id' => 48],
            ['starcraft_id' => 49],
            ['starcraft_id' => 50],
            ['starcraft_id' => 51],
            ['starcraft_id' => 52],
            ['starcraft_id' => 53],
            ['starcraft_id' => 54],
            ['starcraft_id' => 55],
            ['starcraft_id' => 56],
            ['starcraft_id' => 57],
            ['starcraft_id' => 58],
            ['starcraft_id' => 59],
            ['starcraft_id' => 60],
            ['starcraft_id' => 61],
            ['starcraft_id' => 62],
            ['starcraft_id' => 63],
            ['starcraft_id' => 64],
            ['starcraft_id' => 65],
            ['starcraft_id' => 66],
            ['starcraft_id' => 67],
            ['starcraft_id' => 68],
            ['starcraft_id' => 69],
            ['starcraft_id' => 70],
            ['starcraft_id' => 71],
            ['starcraft_id' => 72],
            ['starcraft_id' => 73],
            ['starcraft_id' => 74],
            ['starcraft_id' => 75],
            ['starcraft_id' => 76],
            ['starcraft_id' => 77],
            ['starcraft_id' => 78],
            ['starcraft_id' => 79],
            ['starcraft_id' => 80],
            ['starcraft_id' => 81],
            ['starcraft_id' => 82],
            ['starcraft_id' => 83],
            ['starcraft_id' => 84],
            ['starcraft_id' => 85],
            ['starcraft_id' => 86],
            ['starcraft_id' => 87],
            ['starcraft_id' => 88],
            ['starcraft_id' => 89],
            ['starcraft_id' => 90],
            ['starcraft_id' => 91],
            ['starcraft_id' => 92],
            ['starcraft_id' => 93],
            ['starcraft_id' => 94],
            ['starcraft_id' => 95],
            ['starcraft_id' => 96],
            ['starcraft_id' => 97],
            ['starcraft_id' => 98],
            ['starcraft_id' => 99],
            ['starcraft_id' => 100],
            ['starcraft_id' => 101],
            ['starcraft_id' => 102],
            ['starcraft_id' => 103],
            ['starcraft_id' => 104],
            ['starcraft_id' => 105],
            ['starcraft_id' => 106],
            ['starcraft_id' => 107],
            ['starcraft_id' => 108],
            ['starcraft_id' => 109],
            ['starcraft_id' => 110],
            ['starcraft_id' => 111],
            ['starcraft_id' => 112],
            ['starcraft_id' => 113],
            ['starcraft_id' => 114],
            ['starcraft_id' => 115],
            ['starcraft_id' => 116],
            ['starcraft_id' => 117],
            ['starcraft_id' => 118],
            ['starcraft_id' => 119],
            ['starcraft_id' => 120],
            ['starcraft_id' => 121],
            ['starcraft_id' => 122],
            ['starcraft_id' => 123],
            ['starcraft_id' => 124],

        ]);
    }
}
